load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "condition-emitter",
    srcs = ["condition-emitter.cc"],
    hdrs = ["condition-emitter.h"],
    visibility = ["//visibility:public"],
    deps = ["//ces:event-emitter"],
)
