load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "timeout-emitter",
    srcs = ["timeout-emitter.cc"],
    hdrs = ["timeout-emitter.h"],
    visibility = ["//visibility:public"],
    deps = ["//ces:event-emitter"],
)
