load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "event-emitter",
    hdrs = ["event-emitter.h"],
    visibility = ["//visibility:public"],
    deps = ["//ces/utils:awaitable-data"],
)
